### PR TITLE
Update simulate.py-current_fraction_solid value

### PR DESCRIPTION
**Pull request by HUISUN24**

### CODE REVIEW

**Comment by bocklund** [comment]
Can you provide an example that triggers the bug and is fixed by the change?

**Comment by HUISUN24** [comment]
Hi Brandon,

The jupyter notebook and the tdb file is in the attachment.
When the initial temperature is lower than the melting temperature,
Instead of error "UnboundLocalError: local variable
'current_fraction_solid' referenced before assignment"
it will give an output.

Best,
Hui Sun

**Comment by bocklund** [comment]
Can you drag and drop them into the GH issue or send to me separately? I don't think they attach properly when you respond to the GitHub emails.

**Comment by HUISUN24** [comment]
[test_scheil.zip](https://github.com/pycalphad/scheil/files/11895901/test_scheil.zip)
I compressed the tdb and the jupyter notebook into the zip file since GH does not allow these file types

**Comment by bocklund** [comment]
Running the example with verbose on gives the following output:

```
building PhaseRecord objects... done
generating points... BCC_A2 CUB_A13 DELTA EPSILON ETA FCC_A1 GAMMA_D83 GAMMA_H GAS HCP_A3 LIQUID THETA ZETA done
Adding points to FCC_A1. New phases seen: {'FCC_A1'}. No liquid phase found at T=1060.000, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.167, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.306, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.421, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.518, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.598, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.665, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.721, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.767, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Stepping back and reducing step size.
Adding points to FCC_A1. No liquid phase found at T=1060.806, X_AG=1.00, X_AL=0.00. (Found {'FCC_A1'}) Maximum step size reduction exceeded. Stopping.
```

The root cause appears to be that the starting point has no liquid, which seems to trigger this bug as the code assumes some liquid will be found. Probably what should be done is that if the starting point has no liquid, then we need to report an error instead of what this will do, which is instantly solidifying, which doesn't really make sense to me.

**Comment by HUISUN24** [comment]
I agree, we could give some error message instead of the one here to give more details

**Comment by bocklund** [comment]
Do you feel comfortable making that change to supersede this one?

**Comment by HUISUN24** [comment]
Yean, I will make the change by raising the error when not detecting the liquid phase. I will close this pull request and open a new one when I finish the change

**Pull request closed without merging**
